language: node_js
node_js:
  - 0.10

before_script:
  - npm install grunt-cli -g
  - npm install
  - ./node_modules/.bin/bower install

script:
  - npm test

after_success:
  - grunt coveralls

cache:
  directories:
    - node_modules
    - bower_components
